// Villes proposées pour la localisation (France).
export const wilayas = [
  "Paris",
  "Marseille",
  "Lyon",
  "Toulouse",
  "Nice",
  "Nantes",
  "Strasbourg",
  "Montpellier",
  "Bordeaux",
  "Lille",
  "Rennes",
  "Reims",
  "Toulon",
  "Saint-Étienne",
  "Le Havre",
  "Grenoble",
  "Dijon",
  "Angers",
  "Nîmes",
  "Villeurbanne",
  "Clermont-Ferrand",
  "Le Mans",
  "Aix-en-Provence",
  "Brest",
  "Tours",
  "Amiens",
  "Limoges",
  "Metz",
  "Besançon",
  "Perpignan",
  "Orléans",
  "Rouen",
  "Mulhouse",
  "Caen",
  "Nancy",
  "Roubaix",
  "Tourcoing",
  "Nanterre",
  "Créteil",
  "Argenteuil",
  "Montreuil",
  "Aubervilliers",
  "Saint-Denis",
];
